# Module 1: Pandas Fundamentals

Topics Covered:
- 1.1 Why Pandas? (Data structures: Series & DataFrame vs Python dicts & NumPy arrays)
- 1.2 Environment & Conventions (import pandas as pd, version verification)
- 1.3 Series Architecture (1D labelled array, indexes, dtype)
- 1.4 DataFrame Creation (from dict of lists, list of dicts, 2D NumPy array, records)
- 1.5 Core Inspection Attributes (.shape, .columns, .index, .dtypes, .ndim, .size)
- 1.6 Column Selection (single bracket Series vs double bracket DataFrame)
- 1.7 Row & Cell Selection (.loc[] label-based vs .iloc[] integer position-based)
- 1.8 Setting, Resetting & Renaming Indexes & Columns
- 1.9 Adding, Modifying & Dropping Columns and Rows
- 1.10 Practice Challenge for you to solve with complete solution!

In [1]:
import numpy as np
import pandas as pd

#### 1.1 Why Pandas? (The Tabular Data Workhorse)

In [2]:
# Comparison for Backend / Full-Stack Developers:
# - Python dict: { "id": 1, "name": "Fish" } -> Good for single objects, terrible for 1M rows.
# - NumPy ndarray: Homogeneous raw C-buffer -> Blazing fast for math, but NO column names or mixed types.
# - Pandas DataFrame: Tabular relational structure -> 2D table with heterogeneous typed columns,
#   named headers, explicit row index, missing value awareness, and SQL-like expressive queries.

In [3]:
print(f"Pandas Version: {pd.__version__}")
print(f"NumPy Version:  {np.__version__}")

Pandas Version: 3.0.6
NumPy Version:  2.5.3


#### 1.2 Pandas Series (1D Labelled Array)

In [ ]:
# A Series is a 1D labelled array capable of holding any data type (integers, strings, floats, objects).
# Unlike a NumPy 1D array, a Series has an explicit index (labels).

In [5]:
# Creating from a Python list:

prices = pd.Series([450.0, 720.5, 310.0, 600.0], name="unit_price")
print("Series from list:\n", prices)
print(f"Series dtype: {prices.dtype}, shape: {prices.shape}, name: {prices.name}")

Series from list:
 0    450.0
1    720.5
2    310.0
3    600.0
Name: unit_price, dtype: float64
Series dtype: float64, shape: (4,), name: unit_price


In [11]:
# Creating from a dictionary with custom string indexes (like primary keys):

stock_levels = pd.Series(
    {"SKU-101": 50, "SKU-102": 12, "SKU-103": 0, "SKU-104": 85},
    name="stock_qty"
)

print("\nSeries with custom string index:\n", stock_levels)
print("Access by index label 'SKU-102':", stock_levels["SKU-102"])
print("Summary stats of series:\n", stock_levels.describe())



Series with custom string index:
 SKU-101    50
SKU-102    12
SKU-103     0
SKU-104    85
Name: stock_qty, dtype: int64
Access by index label 'SKU-102': 12
Summary stats of series:
 count     4.000000
mean     36.750000
std      38.586483
min       0.000000
25%       9.000000
50%      31.000000
75%      58.750000
max      85.000000
Name: stock_qty, dtype: float64


#### 1.3 Creating DataFrames (2D Heterogeneous Table)

In [13]:
# Method A: Dict of lists (Most common for mock data & tests)
data_dict = {
    "product_id": [101, 102, 103, 104, 105],
    "product_name": ["Pomfret", "Tiger Prawns", "Kingfish", "Bombay Duck", "Crab"],
    "category": ["Fish", "Shellfish", "Fish", "Fish", "Shellfish"],
    "unit_price": [750.0, 950.0, 800.0, 350.0, 600.0],
    "stock_qty": [25, 40, 15, 60, 30],
    "is_active": [True, True, True, False, True]
}
df_from_dict  = pd.DataFrame(data_dict)
print("DataFrame from Dict of Lists:\n", df_from_dict)

DataFrame from Dict of Lists:
    product_id  product_name   category  unit_price  stock_qty  is_active
0         101       Pomfret       Fish       750.0         25       True
1         102  Tiger Prawns  Shellfish       950.0         40       True
2         103      Kingfish       Fish       800.0         15       True
3         104   Bombay Duck       Fish       350.0         60      False
4         105          Crab  Shellfish       600.0         30       True


In [14]:
# Method B: List of Dictionaries (Matches JSON API payloads / MongoDB docs)

api_records = [
    {"user_id": "u1", "email": "alice@example.com", "total_orders": 5},
    {"user_id": "u2", "email": "bob@example.com", "total_orders": 12},
    {"user_id": "u3", "email": "carol@example.com", "total_orders": 1},
]

df_from_records = pd.DataFrame(api_records)
print("\nDataFrame from List of Dicts (API response format):\n", df_from_records)


DataFrame from List of Dicts (API response format):
   user_id              email  total_orders
0      u1  alice@example.com             5
1      u2    bob@example.com            12
2      u3  carol@example.com             1


In [18]:
# Method C: From a 2D NumPy array with custom column names

matrix = np.random.default_rng(42).integers(10,100, size=(3,3))

print(f"matrix :\n {matrix}")

matrix :
 [[18 79 68]
 [49 48 87]
 [17 72 28]]


#### 1.4 Core DataFrame Attributes (Inspection)

In [30]:
df = df_from_dict.copy()

print("df (rows, cols):", df)
print("df.shape (rows, cols):", df.shape)
print("df.columns:           ", list(df.columns))
print("df.index:             ", df.index)
print("df.dtypes:\n", df.dtypes)
print(f"df.ndim: {df.ndim}, df.size (total cells): {df.size}")
print(f"Underlying raw NumPy buffer values:\n{df[['unit_price', 'stock_qty']].values}")


df (rows, cols):    product_id  product_name   category  unit_price  stock_qty  is_active
0         101       Pomfret       Fish       750.0         25       True
1         102  Tiger Prawns  Shellfish       950.0         40       True
2         103      Kingfish       Fish       800.0         15       True
3         104   Bombay Duck       Fish       350.0         60      False
4         105          Crab  Shellfish       600.0         30       True
df.shape (rows, cols): (5, 6)
df.columns:            ['product_id', 'product_name', 'category', 'unit_price', 'stock_qty', 'is_active']
df.index:              RangeIndex(start=0, stop=5, step=1)
df.dtypes:
 product_id        int64
product_name        str
category            str
unit_price      float64
stock_qty         int64
is_active          bool
dtype: object
df.ndim: 2, df.size (total cells): 30
Underlying raw NumPy buffer values:
[[750.  25.]
 [950.  40.]
 [800.  15.]
 [350.  60.]
 [600.  30.]]


#### 1.5 Column Selection (Series vs DataFrame)

In [31]:
# Single bracket df['col'] returns a 1D Pandas Series
col_series = df["product_name"]
print("Single bracket -> Series:\n", type(col_series), "\n", col_series.head(2))

Single bracket -> Series:
 <class 'pandas.Series'> 
 0         Pomfret
1    Tiger Prawns
Name: product_name, dtype: str


In [33]:
# Double bracket df[['col']] returns a 2D Pandas DataFrame
col_dataframe = df[["product_name"]]
print("\nDouble bracket single col -> DataFrame:\n", type(col_dataframe), "\n", col_dataframe.head(2))

# Double bracket multiple cols -> DataFrame projection (like SQL SELECT col1, col2)
subset = df[["product_name", "unit_price", "stock_qty"]]
print("\nMultiple columns projection:\n", subset)



Double bracket single col -> DataFrame:
 <class 'pandas.DataFrame'> 
    product_name
0       Pomfret
1  Tiger Prawns

Multiple columns projection:
    product_name  unit_price  stock_qty
0       Pomfret       750.0         25
1  Tiger Prawns       950.0         40
2      Kingfish       800.0         15
3   Bombay Duck       350.0         60
4          Crab       600.0         30


#### 1.6 Row & Cell Selection (.loc[] vs .iloc[])

In [37]:
# Rule of Thumb:
# .loc[row_label, col_label]  -> Access by names / labels (inclusive of stop bound!)
# .iloc[row_idx, col_idx]     -> Access by 0-based integer positions (standard Python slice, stop is exclusive!)

print("First row by integer position (.iloc[0]):\n", df.iloc[0])

print("\nFirst 3 rows, specific columns by integer position (.iloc[0:3, 1:4]):\n",
      df.iloc[0:3, 1:4])

print("\nFirst row by label (.loc[0, 'product_name']):", df.loc[0, "product_name"])

print("Rows 0 through 2 (inclusive!) by label with .loc[0:2, ['product_name', 'unit_price']]:\n",
      df.loc[0:2, ["product_name", "unit_price"]])


First row by integer position (.iloc[0]):
 product_id          101
product_name    Pomfret
category           Fish
unit_price        750.0
stock_qty            25
is_active          True
Name: 0, dtype: object

First 3 rows, specific columns by integer position (.iloc[0:3, 1:4]):
    product_name   category  unit_price
0       Pomfret       Fish       750.0
1  Tiger Prawns  Shellfish       950.0
2      Kingfish       Fish       800.0

First row by label (.loc[0, 'product_name']): Pomfret
Rows 0 through 2 (inclusive!) by label with .loc[0:2, ['product_name', 'unit_price']]:
    product_name  unit_price
0       Pomfret       750.0
1  Tiger Prawns       950.0
2      Kingfish       800.0


#### 1.7 Setting, Resetting & Renaming Indexes and Columns

In [41]:
# Set product_id as the DataFrame index (like a Primary Key in SQL):
df_indexed = df.set_index("product_id")
print("DataFrame with 'product_id' as index:\n", df_indexed.head(3))
print("Querying by product_id index label 102:\n", df_indexed.loc[102])


DataFrame with 'product_id' as index:
             product_name   category  unit_price  stock_qty  is_active
product_id                                                           
101              Pomfret       Fish       750.0         25       True
102         Tiger Prawns  Shellfish       950.0         40       True
103             Kingfish       Fish       800.0         15       True
Querying by product_id index label 102:
 product_name    Tiger Prawns
category           Shellfish
unit_price             950.0
stock_qty                 40
is_active               True
Name: 102, dtype: object


In [42]:
# Reset index back to default auto-increment integer:
df_reset = df_indexed.reset_index()
print("\nReset back to integer index:\n", df_reset.head(2))


Reset back to integer index:
    product_id  product_name   category  unit_price  stock_qty  is_active
0         101       Pomfret       Fish       750.0         25       True
1         102  Tiger Prawns  Shellfish       950.0         40       True


In [43]:
# Renaming columns (dict mapping old_name -> new_name):
df_renamed = df.rename(columns={
    "product_name": "name",
    "unit_price": "price_inr",
    "stock_qty": "inventory_count"
})
print("\nRenamed columns:\n", df_renamed.columns.tolist())


Renamed columns:
 ['product_id', 'name', 'category', 'price_inr', 'inventory_count', 'is_active']


#### 1.8 Adding, Modifying & Dropping Columns and Rows

In [44]:
# Adding a calculated column (Vectorized - no loops!):
df["total_inventory_value"] = df["unit_price"] * df["stock_qty"]
print("Added 'total_inventory_value':\n", df[["product_name", "unit_price", "stock_qty", "total_inventory_value"]])


Added 'total_inventory_value':
    product_name  unit_price  stock_qty  total_inventory_value
0       Pomfret       750.0         25                18750.0
1  Tiger Prawns       950.0         40                38000.0
2      Kingfish       800.0         15                12000.0
3   Bombay Duck       350.0         60                21000.0
4          Crab       600.0         30                18000.0


In [45]:
# Modifying column conditionally using np.where:
# (CASE WHEN unit_price >= 800 THEN 'Premium' ELSE 'Standard' END)
df["tier"] = np.where(df["unit_price"] >= 800.0, "Premium", "Standard")
print("\nConditional column 'tier':\n", df[["product_name", "unit_price", "tier"]])


Conditional column 'tier':
    product_name  unit_price      tier
0       Pomfret       750.0  Standard
1  Tiger Prawns       950.0   Premium
2      Kingfish       800.0   Premium
3   Bombay Duck       350.0  Standard
4          Crab       600.0  Standard


In [46]:
# Dropping columns:
df_dropped = df.drop(columns=["is_active", "tier"])
print("\nAfter dropping columns:\n", df_dropped.columns.tolist())


After dropping columns:
 ['product_id', 'product_name', 'category', 'unit_price', 'stock_qty', 'total_inventory_value']


In [47]:
# Dropping rows by index label:
df_dropped_row = df.drop(index=[3])  # Drop row at index 3 (Bombay Duck)
print(f"\nOriginal row count: {len(df)}, row count after dropping index 3: {len(df_dropped_row)}")


Original row count: 5, row count after dropping index 3: 4


####  1.9 Hands-on Practice Challenge

In [ ]:
print("""
PRACTICE EXERCISE:
1. Create a DataFrame representing 4 SaaS subscription plans:
   - plan_id: [1, 2, 3, 4]
   - plan_name: ["Free", "Starter", "Pro", "Enterprise"]
   - monthly_fee: [0, 29, 99, 299]
   - max_users: [1, 5, 25, 100]
   - is_popular: [False, False, True, False]
2. Set 'plan_id' as the index.
3. Add a column 'annual_fee_discounted' representing the annual price with a 20% discount:
   (monthly_fee * 12 * 0.80).
4. Use .loc[] to select all rows where 'monthly_fee' > 0 and display only 'plan_name' and 'annual_fee_discounted'.
5. Drop the 'is_popular' column.
""")

In [ ]:
# --- Challenge Solution ---
plans_df = pd.DataFrame({
    "plan_id": [1, 2, 3, 4],
    "plan_name": ["Free", "Starter", "Pro", "Enterprise"],
    "monthly_fee": [0, 29, 99, 299],
    "max_users": [1, 5, 25, 100],
    "is_popular": [False, False, True, False]
})

# Step 2: Set index
plans_df = plans_df.set_index("plan_id")

# Step 3: Add calculated column
plans_df["annual_fee_discounted"] = plans_df["monthly_fee"] * 12 * 0.80

# Step 4: Use .loc with boolean mask
paid_plans = plans_df.loc[plans_df["monthly_fee"] > 0, ["plan_name", "annual_fee_discounted"]]
print("Paid Plans Annual Pricing:\n", paid_plans)

# Step 5: Drop column
plans_df = plans_df.drop(columns=["is_popular"])
print("\nFinal Plans DataFrame:\n", plans_df)
print("\n Module 1 Completed Successfully!")